---
title: "San Francisco Parks with Great Views"
author: "MNeisler"
date: "November 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Package Installation

First, we install the required packages. 

```{r}
install.packages("leaflet")
library(leaflet)
```

### Making a Unique Icon
```{r}
sfparkIcon <- makeIcon(
  iconUrl = "http://sfrecpark.org/wp-content/uploads/SF_RecPark_Logo4.png",
  iconWidth = 31*215/230, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16
)
```

### Creating the data frame
```{r}
set.seed(2016-11-06)
df <- data.frame( lat = c(37.7924566, 37.7779316, 37.7684421, 37.7532508, 37.7466678, 37.7523686),
  lng = c(-122.4260578, -122.4488157, -122.4343834,-122.460038, -122.4648874,-122.4734061))
```
 
### Creating Popups
```{r}
sfparkSites <- c(
  "<a href='http://sfrecpark.org/destination/alta-plaza-park/'>Alta Plaza Park</a>",
  "<a href='http://sfrecpark.org/destination/lafayette-park/'>Lafayette Park</a>",
  "<a href='http://sfrecpark.org/destination/buena-vista-park/'>Buena Vista Park</a>",
  "<a href='http://sfrecpark.org/destination/twin-peaks/'>Twin Peaks</a>",
  "<a href='http://sfrecpark.org/destination/mt-davidson-park/'>Mt. Davidson Park</a>",
   "<a href='http://sfrecpark.org/destination/grand-view-park/'>Grand View Park</a>"
)
```

### My Map

```{r, echo=FALSE}
sfpark_map <- df %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = sfparkIcon, popup = sfparkSites)
sfpark_map
```

